name: Build

on:
  push:
    branches: bug/transform-drops-fields

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: cachix-action
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix develop -c pytest
